branches:
  only:
    - master

os:
  - linux

sudo: required

env:
  matrix:
    - export NODE_VERSION="6.11.1"
   # - export NODE_VERSION="7"
   # - export NODE_VERSION="8"

matrix:
  fast_finish: true

git:
  depth: 1

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev
  chrome: stable

before_install:
  - nvm install $NODE_VERSION
  - npm install -g grunt-cli

install:
  - cd modules/orionode;
  - npm install;
  - grunt;
script:
  - npm pack;
  - npm test
after_success:
  - npm run report-coverage
